feat: Writing error message to stderr

diff --git a/docker_promote b/docker_promote
--- a/docker_promote
+++ b/docker_promote
@@ -13,7 +13,7 @@ main() {
   local DOCKER_AUTH_TOKEN="https://auth.docker.io/token?service=registry.docker.io"
 
   if [[ ${#} -lt 2 ]]; then
-    printf "%bUsage: ${0} [IMAGE_NAME] [IMAGE_VERSION] [VERSION_TARGET]%b\n" "${RED}" "${RESET}"
+    printf "%bUsage: ${0} [IMAGE_NAME] [IMAGE_VERSION] [VERSION_TARGET]%b\n" "${RED}" "${RESET}" 1>&2
     return 1
   fi
 
@@ -39,8 +39,8 @@ main() {
   unset DOCKER_PASS
 
   if [[ ${HTTP_STATUS} != "200" ]]; then
-    printf "%bUnable to retrieve token for %s%b\n" "${RED}" "${DOCKER_IMAGE}" "${RESET}"
-    printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
+    printf "%bUnable to retrieve token for %s%b\n" "${RED}" "${DOCKER_IMAGE}" "${RESET}" 1>&2
+    printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
@@ -61,8 +61,8 @@ main() {
     )"
 
     if [[ ${HTTP_STATUS} != "200" ]]; then
-      printf "%bUnable to retrieve manifest for %s%b\n" "${RED}" "${DOCKER_IMAGE}" "${RESET}"
-      printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
+      printf "%bUnable to retrieve manifest for %s%b\n" "${RED}" "${DOCKER_IMAGE}" "${RESET}" 1>&2
+      printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}" 1>&2
       cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
       return
     fi
@@ -79,8 +79,8 @@ main() {
     )"
 
     if [[ ${HTTP_STATUS} != "201" ]]; then
-      printf "%bUnable to promote manifest for %s%b\n" "${RED}" "${DOCKER_IMAGE}" "${RESET}"
-      printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
+      printf "%bUnable to promote manifest for %s%b\n" "${RED}" "${DOCKER_IMAGE}" "${RESET}" 1>&2
+      printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}" 1>&2
       cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
       continue
     fi
diff --git a/docker_registry_cleanup b/docker_registry_cleanup
--- a/docker_registry_cleanup
+++ b/docker_registry_cleanup
@@ -28,8 +28,8 @@ main() {
   unset DOCKER_PASSWORD
 
   if [[ ${HTTP_STATUS} != "200" ]]; then
-    printf "%bUnable to login to registry %s%b\n" "${RED}" "${DOCKER_REGISTRY}" "${RESET}"
-    printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
+    printf "%bUnable to login to registry %s%b\n" "${RED}" "${DOCKER_REGISTRY}" "${RESET}" 1>&2
+    printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
@@ -42,8 +42,8 @@ main() {
 
   HTTP_STATUS="$("${CLIENT_ARGS[@]}" -X GET "${DOCKER_REGISTRY}/users/${DOCKER_OWNER}/repositories/?page_size=100")"
   if [[ ${HTTP_STATUS} != "200" ]]; then
-    printf "%bUnable to list images for %s%b\n" "${RED}" "${DOCKER_OWNER}" "${RESET}"
-    printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
+    printf "%bUnable to list images for %s%b\n" "${RED}" "${DOCKER_OWNER}" "${RESET}" 1>&2
+    printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
@@ -57,8 +57,8 @@ main() {
 
     HTTP_STATUS="$("${CLIENT_ARGS[@]}" -X GET "${DOCKER_REGISTRY}/repositories/${DOCKER_OWNER}/${repository}/tags/?page_size=100")"
     if [[ ${HTTP_STATUS} != "200" ]]; then
-      printf "%bUnable to list tags for %s%b\n" "${RED}" "${DOCKER_OWNER}/${repository}" "${RESET}"
-      printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
+      printf "%bUnable to list tags for %s%b\n" "${RED}" "${DOCKER_OWNER}/${repository}" "${RESET}" 1>&2
+      printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}" 1>&2
       cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
       continue
     fi
@@ -71,8 +71,8 @@ main() {
       if [[ ${tag} =~ ^[0-9A-Fa-f]{6,} ]]; then
         HTTP_STATUS="$("${CLIENT_ARGS[@]}" -X DELETE "${DOCKER_REGISTRY}/repositories/${DOCKER_OWNER}/${repository}/tags/${tag}/")"
         if [[ ${HTTP_STATUS} != "204" ]]; then
-          printf "%bUnable to delete tags for %s%b\n" "${RED}" "${DOCKER_OWNER}/${repository}:${tag}" "${RESET}"
-          printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
+          printf "%bUnable to delete tags for %s%b\n" "${RED}" "${DOCKER_OWNER}/${repository}:${tag}" "${RESET}" 1>&2
+          printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}" 1>&2
           cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
           continue
         fi
diff --git a/github b/github
--- a/github
+++ b/github
@@ -7,7 +7,7 @@ github_repo_stats() {
   var_color
 
   if [[ ${#} -ne 2 ]]; then
-    printf "%bUsage: github_repo_stats owner/repo user%b\n" "${RED}" "${RESET}"
+    printf "%bUsage: github_repo_stats owner/repo user%b\n" "${RED}" "${RESET}" 1>&2
     return 1
   fi
 
@@ -25,7 +25,7 @@ github_repo_stats() {
     rm "${HTTP_OUTPUT}"
     return
   elif [[ ${HTTP_STATUS} != "200" ]]; then
-    printf "%bUnable to get contributors' stats for %s%b\n" "${RED}" "${GITHUB_REPOSITORY}" "${RESET}"
+    printf "%bUnable to get contributors' stats for %s%b\n" "${RED}" "${GITHUB_REPOSITORY}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
@@ -41,7 +41,7 @@ github_org_stats() {
   var_color
 
   if [[ ${#} -ne 2 ]]; then
-    printf "%bUsage: github_org_stats organization_name user%b\n" "${RED}" "${RESET}"
+    printf "%bUsage: github_org_stats organization_name user%b\n" "${RED}" "${RESET}" 1>&2
     return 1
   fi
 
@@ -65,7 +65,7 @@ github_org_stats() {
 
     HTTP_STATUS="$("${CLIENT_ARGS[@]}" "https://api.github.com/orgs/${GITHUB_ORGANIZATION}/repos?per_page=${page_size}&page=${page}")"
     if [[ ${HTTP_STATUS} != "200" ]]; then
-      printf "%bUnable to list organizations repos of %s for page %s%b\n" "${RED}" "${GITHUB_ORGANIZATION}" "${page}" "${RESET}"
+      printf "%bUnable to list organizations repos of %s for page %s%b\n" "${RED}" "${GITHUB_ORGANIZATION}" "${page}" "${RESET}" 1>&2
       cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
       return
     fi
@@ -94,7 +94,7 @@ github_org_stats() {
   output="[${output}]"
   printf "%s\n" "${output}"
 
-  printf "%s" "${output}" | jq '{added: (reduce .[] as $repo (0; . + $repo.added)), deleted: (reduce .[] as $repo (0; . + $repo.deleted)), commits: (reduce .[] as $repo (0; . + $repo.commits))}'
+  printf "%s" "${output}" | jq '{added: (reduce .[] as $repo (0; . + $repo.added)), deleted: (reduce .[] as $repo (0; . + $repo.deleted)), commits: (reduce .[] as $repo (0; . + $repo.commits))} | {added: .added, deleted: .deleted, commits: .commits, ratio: (.added - .deleted), mean_by_commit: ((.added - .deleted) / .commits) | floor}'
 }
 
 github_clone_user() {
@@ -109,7 +109,7 @@ github_clone_user() {
   local HTTP_STATUS
   HTTP_STATUS="$("${CLIENT_ARGS[@]}" "-H" "Content-Type: application/json" "https://api.github.com/user/repos?type=owner&per_page=100")"
   if [[ ${HTTP_STATUS} != "200" ]]; then
-    printf "%bUnable to list user repos%b\n" "${RED}" "${RESET}"
+    printf "%bUnable to list user repos%b\n" "${RED}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
@@ -135,7 +135,7 @@ github_compare_version() {
   var_color
 
   if [[ ${#} -lt 2 ]]; then
-    printf "%bUsage: github_compare_version owner/repo latest_version [current_version] [release_api_output_file]%b\n" "${RED}" "${RESET}"
+    printf "%bUsage: github_compare_version owner/repo latest_version [current_version] [release_api_output_file]%b\n" "${RED}" "${RESET}" 1>&2
     return 1
   fi
 
@@ -164,7 +164,7 @@ github_last_release() {
   var_color
 
   if [[ ${#} -lt 1 ]]; then
-    printf "%bUsage: github_last_release owner/repo [previous_version] %b\n" "${RED}" "${RESET}"
+    printf "%bUsage: github_last_release owner/repo [previous_version] %b\n" "${RED}" "${RESET}" 1>&2
     return 1
   fi
 
@@ -177,7 +177,7 @@ github_last_release() {
   local HTTP_STATUS
   HTTP_STATUS="$("${CLIENT_ARGS[@]}" "https://api.github.com/repos/${1}/releases/latest")"
   if [[ ${HTTP_STATUS} != "200" ]]; then
-    printf "%bUnable to list latest release for %s%b\n" "${RED}" "${1}" "${RESET}"
+    printf "%bUnable to list latest release for %s%b\n" "${RED}" "${1}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
@@ -190,7 +190,7 @@ github_configure() {
   var_color
 
   if [[ ${#} -ne 1 ]]; then
-    printf "%bUsage: configure_repository owner/repo%b\n" "${RED}" "${RESET}"
+    printf "%bUsage: configure_repository owner/repo%b\n" "${RED}" "${RESET}" 1>&2
     return 1
   fi
 
@@ -208,21 +208,21 @@ github_configure() {
     "has_projects": false
   }')"
   if [[ ${HTTP_STATUS} != "200" ]]; then
-    printf "%bUnable to edit ${1}%b\n" "${RED}" "${RESET}"
+    printf "%bUnable to edit ${1}%b\n" "${RED}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
 
   HTTP_STATUS="$("${CLIENT_ARGS[@]}" "-H" "Accept: application/vnd.github.dorian-preview+json" "-X" "PUT" "https://api.github.com/repos/${1}/vulnerability-alerts")"
   if [[ ${HTTP_STATUS} != "204" ]]; then
-    printf "%bUnable to enable vulnerability alerts for ${1}%b\n" "${RED}" "${RESET}"
+    printf "%bUnable to enable vulnerability alerts for ${1}%b\n" "${RED}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
 
   HTTP_STATUS="$("${CLIENT_ARGS[@]}" "-H" "Accept: application/vnd.github.london-preview+json" "-X" "PUT" "https://api.github.com/repos/${1}/automated-security-fixes")"
   if [[ ${HTTP_STATUS} != "204" ]]; then
-    printf "%bUnable to enable automated security fixes for ${1}%b\n" "${RED}" "${RESET}"
+    printf "%bUnable to enable automated security fixes for ${1}%b\n" "${RED}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
@@ -242,14 +242,14 @@ github_configure() {
     "restrictions": null
   }')"
   if [[ ${HTTP_STATUS} != "200" ]]; then
-    printf "%bUnable to update branch protection ${1}%b\n" "${RED}" "${RESET}"
+    printf "%bUnable to update branch protection ${1}%b\n" "${RED}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
 
   HTTP_STATUS="$("${CLIENT_ARGS[@]}" "-H" "Accept: application/vnd.github.zzzax-preview+json" "-X" "POST" "https://api.github.com/repos/${1}/branches/master/protection/required_signatures")"
   if [[ ${HTTP_STATUS} != "200" ]]; then
-    printf "%bUnable to enable required signed commits for ${1}%b\n" "${RED}" "${RESET}"
+    printf "%bUnable to enable required signed commits for ${1}%b\n" "${RED}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     return
   fi
diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -4,8 +4,8 @@ set -o nounset -o pipefail
 
 run_command() {
   if ! "${@}"; then
-    printf "%bCommit Failed%b\n" "${RED}" "${RESET}"
-    printf "%bPlease fix errors and try committing again.%b\n" "${RED}" "${RESET}"
+    printf "%bCommit Failed%b\n" "${RED}" "${RESET}" 1>&2
+    printf "%bPlease fix errors and try committing again.%b\n" "${RED}" "${RESET}" 1>&2
 
     exit 1
   fi
@@ -21,8 +21,8 @@ get_diff() {
 
 diff_check() {
   if [[ ${1} != $(get_diff) ]]; then
-    printf "%bPre-commit has changed files%b\n" "${RED}" "${RESET}"
-    printf "%bConsider adding updated file with %bgit add -i && git commit --amend%b\n" "${RED}" "${BLUE}" "${RESET}"
+    printf "%bPre-commit has changed files%b\n" "${RED}" "${RESET}" 1>&2
+    printf "%bConsider adding updated file with %bgit add -i && git commit --amend%b\n" "${RED}" "${BLUE}" "${RESET}" 1>&2
   fi
 }
 
diff --git a/release b/release
--- a/release
+++ b/release
@@ -14,7 +14,7 @@ golang_build() {
 
   if [[ ${BUILD_WITH_DOCKER:-} == "true" ]]; then
     if ! command -v docker >/dev/null 2>&1; then
-      printf "%bdocker not found%b\n" "${RED}" "${RESET}"
+      printf "%bdocker not found%b\n" "${RED}" "${RESET}" 1>&2
       return
     fi
 
@@ -22,7 +22,7 @@ golang_build() {
     OUTPUT_DIR="/go/src/app/release"
   else
     if ! command -v go >/dev/null 2>&1; then
-      printf "%bgo not found%b\n" "${RED}" "${RESET}"
+      printf "%bgo not found%b\n" "${RED}" "${RESET}" 1>&2
       return
     fi
 
@@ -58,7 +58,7 @@ golang_build() {
 
 docker_build() {
   if ! command -v docker >/dev/null 2>&1; then
-    printf "%bdocker not found%b\n" "${RED}" "${RESET}"
+    printf "%bdocker not found%b\n" "${RED}" "${RESET}" 1>&2
     return
   fi
 
@@ -154,8 +154,8 @@ release() {
     }")"
 
   if [[ ${HTTP_STATUS} != "201" ]]; then
-    printf "%bFailed to create release%b\n" "${RED}" "${RESET}"
-    printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
+    printf "%bUnable to create release%b\n" "${RED}" "${RESET}" 1>&2
+    printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}" 1>&2
     cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
     exit 1
   fi
@@ -177,8 +177,8 @@ release() {
       )"
 
       if [[ ${HTTP_STATUS} != "201" ]]; then
-        printf "%bFailed to upload asset %s%b\n" "${RED}" "${asset}" "${RESET}"
-        printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}"
+        printf "%bUnable to upload asset %s%b\n" "${RED}" "${asset}" "${RESET}" 1>&2
+        printf "%bHTTP/%s%b\n" "${RED}" "${HTTP_STATUS}" "${RESET}" 1>&2
         cat "${HTTP_OUTPUT}" && rm "${HTTP_OUTPUT}"
         exit 1
       fi
diff --git a/version b/version
--- a/version
+++ b/version
@@ -7,7 +7,7 @@ version_value() {
   var_color
 
   if [[ ${#} -lt 2 ]]; then
-    printf "%bversion_value [regex] [files]%b\n" "${RED}" "${RESET}"
+    printf "%bversion_value [regex] [files]%b\n" "${RED}" "${RESET}" 1>&2
     return 1
   fi
 
@@ -54,7 +54,7 @@ version_semver() {
 
   if [[ -n ${CURRENT_VERSION} ]]; then
     if ! [[ ${CURRENT_VERSION} =~ ([a-zA-Z]*)([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
-      printf "%bcannot parse existing version: %s%b\n" "${RED}" "${CURRENT_VERSION}" "${RESET}"
+      printf "%bcannot parse existing version: %s%b\n" "${RED}" "${CURRENT_VERSION}" "${RESET}" 1>&2
       return 2
     fi
 
@@ -66,7 +66,7 @@ version_semver() {
 
   if [[ ${#} -lt 1 ]]; then
     printf "%bCurrent version is: %s%b\n" "${BLUE}" "${PREFIX}${MAJOR}.${MINOR}.${PATCH}" "${RESET}"
-    printf "%bUsage: version_semver [major|minor|patch] [git ref] [quiet]%b\n" "${RED}" "${RESET}"
+    printf "%bUsage: version_semver [major|minor|patch] [git ref] [quiet]%b\n" "${RED}" "${RESET}" 1>&2
     return 3
   fi
 
@@ -87,7 +87,7 @@ version_semver() {
     ;;
 
   *)
-    printf "%bunknown version name: %s%b\n" "${RED}" "${1}" "${RESET}"
+    printf "%bunknown version name: %s%b\n" "${RED}" "${1}" "${RESET}" 1>&2
     return 4
     ;;
   esac
