Adding BUILD_WITH_DOCKER for golang build

diff --git a/release b/release
--- a/release
+++ b/release
@@ -10,9 +10,20 @@ release_clean() {
 }
 
 golang_build() {
-  if ! command -v go > /dev/null 2>&1; then
-    printf "%bgo not found%b\n" "${RED}" "${RESET}"
-    return
+  local GO
+  if [[ ${BUILD_WITH_DOCKER:-} != "true" ]]; then
+    if ! command -v go > /dev/null 2>&1; then
+      printf "%bgo not found%b\n" "${RED}" "${RESET}"
+      return
+    fi
+    GO="go"
+  else
+    if ! command -v docker > /dev/null 2>&1; then
+      printf "%bdocker not found%b\n" "${RED}" "${RESET}"
+      return
+    fi
+
+    GO="docker run -it --rm -w /go/src/app -v /Users/macbook/code/api:/go/src/app -v /Users/macbook/code/api/.docker_cache/bin:/go/bin -v /Users/macbook/code/api/.docker_cache/pkg:/go/pkg -e GOOS=\${GOOS} -e GOARCH=\${GOARCH} -e CGO_ENABLED=\${CGO_ENABLED} golang:1.13 go"
   fi
 
   local TARGETS=('darwin/amd64' 'linux/amd64' 'linux/arm' 'linux/arm64')
@@ -27,15 +38,12 @@ golang_build() {
     for OS_ARCH in "${TARGETS[@]}"; do
       IFS='/' read -r -a context <<< "${OS_ARCH}"
 
-      local GOOS="${context[0]}"
-      local GOARCH="${context[1]}"
-
       (
-        export GOOS="${GOOS}"
-        export GOARCH="${GOARCH}"
-        export CGO_ENABLED=0
+        export GOOS="${context[0]}"
+        export GOARCH="${context[1]}"
+        export CGO_ENABLED="0"
         printf "%bBuilding binary %s to %s%b\n" "${BLUE}" "${NAME}_${GOOS}_${GOARCH}" "${OUTPUT_DIR}" "${RESET}"
-        go build -ldflags="-s -w" -installsuffix nocgo -o "${OUTPUT_DIR}/${NAME}_${GOOS}_${GOARCH}" "${main}"
+        ${GO} build -ldflags="-s -w" -installsuffix nocgo -o "${OUTPUT_DIR}/${NAME}_${GOOS}_${GOARCH}" "${main}"
       )
     done
   done
